### ISSUE TITLE
How to read div id or class

### ISSUE THREAD

**Issue by kossa** [untemps/vocal#15]

**Comment by untemps** [comment]
@kossa What do you mean? The Vocal class has nothing to do with DOM elements. 
You may want to attach a vocal command to a click on an element. If so and if your app is written in React, you may consider [@untemps/react-vocal](https://github.com/untemps/react-vocal).
If not, you can use @untemps/vocal as primitive for a custom implementation.

**Comment by kossa** [comment]
Really I don’t know what I want, I totally forgot 😅
